### ISSUE TITLE
Reinstate attribution from HNS

### ISSUE THREAD

**Issue by Arachnid** [jafri/eosdns-server#1]
Much of this project is clearly derived from handshake-org/hsd; for instance, https://github.com/jafri/eosdns-server/blob/master/src/server.js is clearly a subset of https://github.com/handshake-org/hsd/blob/master/lib/dns/server.js, with almost every remaining line directly corresponding to one from the hns source.

You should reinstate the copyright notices by @chjj and license your own contributions under a license compatible with the original's MIT license.

**Comment by jafri** [comment]
Resolved via 5825268be27ce78aaca30819f51d0d3170d2dddc
